const path = require('path');
const fs = require('fs');
const {
  withDangerousMod,
  withMainApplication,
  withAppBuildGradle,
  createRunOncePlugin,
} = require('expo/config-plugins');

const pkg = { name: 'with-native-qr-scanner', version: '1.0.0' };

const JAVA_PACKAGE = 'com.marzi.staff';

/**
 * Native (Kotlin) QR scanner: CameraX preview + MLKit barcode analysis, with
 * detection, de-duplication and torch control all handled on the native side.
 *
 * WHY THIS EXISTS
 * ---------------
 * The gate-pass scanner is the single most-used screen in the staff app and it
 * was the slowest. With `expo-camera`'s `onBarcodeScanned`, EVERY frame that
 * contains a barcode crosses the JS bridge — MLKit happily reports the same QR
 * 20-30 times a second — and the only thing stopping a flood of duplicate
 * `/visitors/qr/:token` lookups was a React state flag (`scanned`) checked in
 * JS. That guard is set asynchronously, so several lookups for the same code
 * routinely fired before it took effect, and the bridge traffic made the
 * preview stutter while a guard lined up the code.
 *
 * Doing the work natively fixes both halves:
 *   • ImageAnalysis runs on its own executor with STRATEGY_KEEP_ONLY_LATEST,
 *     so a slow frame is dropped rather than queued — the preview never backs
 *     up behind analysis.
 *   • A native de-dupe (same value inside DEBOUNCE_MS is ignored) means JS
 *     receives exactly ONE event per physical scan. No duplicate network calls,
 *     no race with a React state flag.
 *
 * It also unlocks the thing guards actually asked for and expo-camera's
 * barcode path did not expose here: a TORCH. Society gates are unlit after
 * dark and a phone light is the difference between scanning a pass in one
 * second and in fifteen.
 *
 * SAFETY: JS FALLBACK
 * -------------------
 * `src/components/QrScanner.tsx` feature-detects this view and falls back to
 * `expo-camera` when it is absent (iOS, Expo Go, or a JS-only reload against
 * an older native binary). The scanner therefore never hard-depends on this
 * plugin having been applied.
 *
 * WHY A CONFIG PLUGIN
 * -------------------
 * `apps/*​/android/` is gitignored and regenerated by `expo prebuild`, so
 * hand-written Kotlin there is discarded — see withAndroidNoSystemSplash.js.
 *
 * DEPENDENCIES: CameraX and MLKit barcode-scanning are already pulled in by
 * expo-camera, but declared `implementation`, which does NOT put them on the
 * app module's compile classpath. They are therefore re-declared below at the
 * SAME versions expo-camera uses, so Gradle resolves one copy rather than
 * silently upgrading to a mismatched pair.
 */

/** Keep in sync with expo-camera/android/build.gradle. */
const CAMERAX_VERSION = '1.5.0-rc01';
const MLKIT_BARCODE_VERSION = '17.3.0';

const VIEW_KT = `package ${JAVA_PACKAGE}

import android.annotation.SuppressLint
import android.content.Context
import android.util.Log
import android.widget.FrameLayout
import androidx.camera.core.CameraSelector
import androidx.camera.core.ExperimentalGetImage
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.ImageProxy
import androidx.camera.view.LifecycleCameraController
import androidx.camera.view.PreviewView
import androidx.lifecycle.LifecycleOwner
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.ReactContext
import com.facebook.react.uimanager.ThemedReactContext
import com.facebook.react.uimanager.events.RCTEventEmitter
import com.google.mlkit.vision.barcode.BarcodeScanner
import com.google.mlkit.vision.barcode.BarcodeScannerOptions
import com.google.mlkit.vision.barcode.BarcodeScanning
import com.google.mlkit.vision.barcode.common.Barcode
import com.google.mlkit.vision.common.InputImage
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

/**
 * GENERATED by plugins/withNativeQrScanner.js — do not edit in android/.
 *
 * CameraX preview + MLKit QR analysis. Emits exactly one \`onCodeScanned\`
 * event per physical scan; see the plugin header for why that matters.
 *
 * Uses LifecycleCameraController rather than ProcessCameraProvider: the
 * provider API returns a Guava ListenableFuture, and CameraX declares Guava as
 * \`implementation\`, so the type is not even nameable from an app module
 * without vendoring Guava purely to await one future. The controller binds
 * synchronously, owns the preview/analysis use cases itself, and exposes torch
 * directly — less code and one fewer dependency.
 */
@SuppressLint("ViewConstructor")
class MarziQrScannerView(context: Context) : FrameLayout(context) {

  companion object {
    private const val TAG = "MarziQrScanner"
    /**
     * Ignore a repeat of the SAME value inside this window. MLKit re-reports a
     * stationary code every frame; without this JS would see ~25 events/sec.
     * Long enough to cover a guard holding the phone still, short enough that
     * deliberately re-scanning the same pass still works.
     */
    private const val DEBOUNCE_MS = 2500L
  }

  private val previewView = PreviewView(context).apply {
    // COMPATIBLE (TextureView) rather than PERFORMANCE (SurfaceView): React
    // Native composites views into its own hierarchy, and a SurfaceView punches
    // a hole through anything drawn above it — the scan frame overlay and
    // header would disappear on some devices.
    implementationMode = PreviewView.ImplementationMode.COMPATIBLE
    scaleType = PreviewView.ScaleType.FILL_CENTER
  }

  private var analysisExecutor: ExecutorService? = null
  private var controller: LifecycleCameraController? = null
  private var scanner: BarcodeScanner? = null

  private var lastValue: String? = null
  private var lastAt: Long = 0L

  /** When true, frames are still analysed but results are not emitted. */
  var paused: Boolean = false

  var torch: Boolean = false
    set(value) {
      field = value
      // No-op (and logs) if the device has no flash unit.
      runCatching { controller?.enableTorch(value) }
    }

  init {
    addView(previewView, LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT))
  }

  override fun onDetachedFromWindow() {
    stop()
    super.onDetachedFromWindow()
  }

  /**
   * React Native's ViewGroup SWALLOWS requestLayout() from children: its
   * layout is computed on the shadow-tree thread, so a child asking to be
   * re-laid-out is ignored. A PreviewView backed by a TextureView therefore
   * never gets a real layout pass, never produces a SurfaceTexture, and
   * CameraX waits forever for the preview Surface:
   *
   *   Camera2CameraImpl: Unable to configure camera
   *   TimeoutException: Future[...] is not done within 5000 ms
   *
   * — camera OPENED, preview permanently black. Re-posting our own
   * measure+layout is the documented workaround for hosting native Android
   * views inside RN.
   */
  private val measureAndLayout = Runnable {
    measure(
      MeasureSpec.makeMeasureSpec(width, MeasureSpec.EXACTLY),
      MeasureSpec.makeMeasureSpec(height, MeasureSpec.EXACTLY),
    )
    layout(left, top, right, bottom)
  }

  override fun requestLayout() {
    super.requestLayout()
    post(measureAndLayout)
  }

  /**
   * React Native does not lay out children of a custom ViewGroup, so the
   * preview would stay 0x0 and render black. Measure/layout it manually — the
   * approach the RN docs prescribe for wrapped native views.
   *
   * The camera is ALSO started from here, not from onAttachedToWindow().
   * RN attaches a view before it has run layout on it, so at attach time
   * previewView is still 0x0; PreviewView will not hand CameraX a Surface at
   * that size, and bindToLifecycle then fails with
   *
   *   Camera2CameraImpl: Unable to configure camera
   *   TimeoutException: Future[...] is not done within 5000 ms
   *
   * and the preview stays black forever. Waiting for the first non-zero layout
   * guarantees there is a real surface to bind.
   */
  override fun onLayout(changed: Boolean, l: Int, t: Int, r: Int, b: Int) {
    super.onLayout(changed, l, t, r, b)
    val w = r - l
    val h = b - t
    previewView.measure(
      MeasureSpec.makeMeasureSpec(w, MeasureSpec.EXACTLY),
      MeasureSpec.makeMeasureSpec(h, MeasureSpec.EXACTLY),
    )
    previewView.layout(0, 0, w, h)
    if (w > 0 && h > 0) start()
  }

  private fun start() {
    if (controller != null) return
    val owner = (context as? ThemedReactContext)?.currentActivity as? LifecycleOwner
    if (owner == null) {
      Log.w(TAG, "No LifecycleOwner activity; camera not started")
      return
    }
    try {
      val executor = Executors.newSingleThreadExecutor().also { analysisExecutor = it }
      scanner = BarcodeScanning.getClient(
        BarcodeScannerOptions.Builder()
          // QR only — restricting the format set measurably cuts per-frame
          // work versus scanning every symbology MLKit supports.
          .setBarcodeFormats(Barcode.FORMAT_QR_CODE)
          .build(),
      )

      val c = LifecycleCameraController(context).apply {
        cameraSelector = CameraSelector.DEFAULT_BACK_CAMERA
        // Preview + analysis only. Binding the capture/video use cases would
        // reserve camera resources this screen never uses.
        setEnabledUseCases(LifecycleCameraController.IMAGE_ANALYSIS)
        // Drop stale frames rather than queueing them: the preview must never
        // wait on analysis.
        imageAnalysisBackpressureStrategy = ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST
        setImageAnalysisAnalyzer(executor, ::analyze)
      }
      controller = c
      previewView.controller = c
      c.bindToLifecycle(owner)
      runCatching { c.enableTorch(torch) }
    } catch (t: Throwable) {
      Log.e(TAG, "Failed to start camera", t)
      stop()
    }
  }

  @OptIn(ExperimentalGetImage::class)
  private fun analyze(proxy: ImageProxy) {
    val media = proxy.image
    val client = scanner
    if (media == null || client == null) {
      proxy.close()
      return
    }
    val image = InputImage.fromMediaImage(media, proxy.imageInfo.rotationDegrees)
    client.process(image)
      .addOnSuccessListener { codes ->
        val value = codes.firstOrNull()?.rawValue
        if (!value.isNullOrEmpty()) emit(value)
      }
      .addOnCompleteListener {
        // MUST close on every path or CameraX stops delivering frames once the
        // buffer fills — the classic "scanner works for a second then freezes".
        proxy.close()
      }
  }

  /** De-duplicated emit. See DEBOUNCE_MS. */
  private fun emit(value: String) {
    if (paused) return
    val now = System.currentTimeMillis()
    if (value == lastValue && now - lastAt < DEBOUNCE_MS) return
    lastValue = value
    lastAt = now

    val reactContext = context as? ReactContext ?: return
    val payload = Arguments.createMap().apply { putString("data", value) }
    reactContext
      .getJSModule(RCTEventEmitter::class.java)
      .receiveEvent(id, "onCodeScanned", payload)
  }

  private fun stop() {
    runCatching { controller?.clearImageAnalysisAnalyzer() }
    runCatching { controller?.unbind() }
    runCatching { scanner?.close() }
    runCatching { analysisExecutor?.shutdown() }
    previewView.controller = null
    controller = null
    scanner = null
    analysisExecutor = null
  }
}
`;

const VIEW_MANAGER_KT = `package ${JAVA_PACKAGE}

import com.facebook.react.uimanager.SimpleViewManager
import com.facebook.react.uimanager.ThemedReactContext
import com.facebook.react.uimanager.annotations.ReactProp

/**
 * GENERATED by plugins/withNativeQrScanner.js.
 *
 * Classic SimpleViewManager because this app runs the OLD architecture
 * (\`newArchEnabled: false\`, required by the splash-hang fix).
 */
class MarziQrScannerViewManager : SimpleViewManager<MarziQrScannerView>() {

  override fun getName(): String = REACT_CLASS

  override fun createViewInstance(context: ThemedReactContext): MarziQrScannerView =
    MarziQrScannerView(context)

  @ReactProp(name = "torch")
  fun setTorch(view: MarziQrScannerView, value: Boolean) {
    view.torch = value
  }

  @ReactProp(name = "paused")
  fun setPaused(view: MarziQrScannerView, value: Boolean) {
    view.paused = value
  }

  override fun getExportedCustomDirectEventTypeConstants(): MutableMap<String, Any> =
    mutableMapOf(
      "onCodeScanned" to mutableMapOf("registrationName" to "onCodeScanned"),
    )

  override fun onDropViewInstance(view: MarziQrScannerView) {
    // Releasing the camera is driven by onDetachedFromWindow, but RN can drop
    // a view without detaching it in some teardown orders.
    view.paused = true
    super.onDropViewInstance(view)
  }

  companion object {
    const val REACT_CLASS = "MarziQrScannerView"
  }
}
`;

const PACKAGE_KT = `package ${JAVA_PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * GENERATED by plugins/withNativeQrScanner.js.
 *
 * Separate from MarziNativePackage so the QR scanner and the notification
 * bridge stay independently removable.
 */
class MarziQrPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    emptyList()

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    listOf(MarziQrScannerViewManager())
}
`;

const FILES = {
  'MarziQrScannerView.kt': VIEW_KT,
  'MarziQrScannerViewManager.kt': VIEW_MANAGER_KT,
  'MarziQrPackage.kt': PACKAGE_KT,
};

const withKotlinSources = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        ...JAVA_PACKAGE.split('.'),
      );
      fs.mkdirSync(dir, { recursive: true });
      for (const [name, contents] of Object.entries(FILES)) {
        fs.writeFileSync(path.join(dir, name), contents, 'utf8');
      }
      return cfg;
    },
  ]);

const withPackageRegistration = (config) =>
  withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (!src.includes('MarziQrPackage()')) {
      const anchor = 'PackageList(this).packages.apply {';
      if (!src.includes(anchor)) {
        throw new Error(
          '[with-native-qr-scanner] Could not find PackageList anchor in MainApplication',
        );
      }
      src = src.replace(anchor, `${anchor}\n              add(MarziQrPackage())`);
    }
    cfg.modResults.contents = src;
    return cfg;
  });

/**
 * CameraX + MLKit on the app module's compile classpath. expo-camera already
 * resolves these at runtime but declares them `implementation`, so they are not
 * visible to app-local Kotlin. Versions are pinned to expo-camera's to avoid
 * Gradle resolving two different CameraX versions into one APK.
 */
const DEPS_BEGIN = '// >>> marzi-qr-scanner deps (generated)';
const DEPS_END = '// <<< marzi-qr-scanner deps';

/**
 * CameraX + MLKit on the app module's compile classpath. expo-camera already
 * resolves these at runtime but declares them `implementation`, so they are not
 * visible to app-local Kotlin. Versions are pinned to expo-camera's to avoid
 * Gradle resolving two different CameraX versions into one APK.
 *
 * The block is delimited and REPLACED rather than appended-once. A non-clean
 * `expo prebuild` MERGES build.gradle instead of regenerating it, so a plain
 * "already contains marker → skip" guard would pin the file to whatever the
 * first run wrote and silently ignore every later edit to this list.
 */
const withCameraDependencies = (config) =>
  withAppBuildGradle(config, (cfg) => {
    const block = `
dependencies {
    ${DEPS_BEGIN}
    implementation "androidx.camera:camera-core:${CAMERAX_VERSION}"
    implementation "androidx.camera:camera-camera2:${CAMERAX_VERSION}"
    implementation "androidx.camera:camera-lifecycle:${CAMERAX_VERSION}"
    implementation "androidx.camera:camera-view:${CAMERAX_VERSION}"
    implementation "com.google.mlkit:barcode-scanning:${MLKIT_BARCODE_VERSION}"
    // CameraX's torch/bind APIs return a Guava ListenableFuture, so the type
    // must be NAMEABLE at compile time. Guava is already inside the APK
    // (CameraX depends on it); it is just declared \`implementation\`, which
    // hides it from this module. compileOnly restores visibility and adds
    // nothing to the APK.
    compileOnly "com.google.guava:guava:33.3.1-android"
    ${DEPS_END}
}
`;
    let contents = cfg.modResults.contents;
    // Drop a previously generated block (including its wrapping dependencies{})
    const re = new RegExp(
      `\\n?dependencies \\{\\s*${DEPS_BEGIN.replace(/[.*+?^$()|[\]\\]/g, '\\$&')}[\\s\\S]*?${DEPS_END.replace(/[.*+?^$()|[\]\\]/g, '\\$&')}\\s*\\}\\n?`,
      'g',
    );
    contents = contents.replace(re, '\n');
    cfg.modResults.contents = contents + block;
    return cfg;
  });

const withNativeQrScanner = (config) =>
  withCameraDependencies(withPackageRegistration(withKotlinSources(config)));

module.exports = createRunOncePlugin(withNativeQrScanner, pkg.name, pkg.version);
