const path = require('path');
const fs = require('fs');
const {
  withDangerousMod,
  withMainApplication,
  withAndroidManifest,
  createRunOncePlugin,
} = require('expo/config-plugins');

const pkg = { name: 'with-native-notifications', version: '1.0.0' };

const JAVA_PACKAGE = 'com.marzi.staff';

/**
 * Native (Kotlin) notification channel bootstrap + diagnostics bridge.
 *
 * WHY THIS EXISTS
 * ---------------
 * Channels were created only from JS, inside `registerForPushNotifications()`,
 * which runs *after* the user logs in AND grants POST_NOTIFICATIONS. That
 * leaves a window — every fresh install, and every cold start where FCM
 * launches the process to deliver a push to a killed app — in which the
 * channel a message targets DOES NOT EXIST YET.
 *
 * Android's behaviour in that window is the bug users actually feel:
 *   • FCM falls back to the channel named by the
 *     `default_notification_channel_id` manifest meta-data. That meta-data was
 *     ABSENT, so FCM used its own auto-created "Miscellaneous" channel —
 *     IMPORTANCE_DEFAULT, no heads-up pop, no custom vibration.
 *   • `emergency_sos` (IMPORTANCE_MAX + bypassDnd) therefore did not exist when
 *     the first SOS arrived, so the one notification that must always break
 *     through arrived as a silent tray entry.
 *   • Channel importance is LOCKED at creation time. Once Android has created
 *     "Miscellaneous" for this app, later JS calls cannot upgrade it.
 *
 * Creating the channels in `Application.onCreate` fixes all three: the process
 * that FCM spins up to deliver a push runs `onCreate` *before* the message is
 * dispatched, so every channel is guaranteed to exist with the right
 * importance, vibration pattern and DND policy at the moment of first delivery
 * — with no dependency on the JS bundle having loaded or the user having
 * logged in.
 *
 * It is also faster: `setupAndroidChannels()` in JS was ~14 sequential async
 * bridge round-trips on every login. JS now skips them entirely when this
 * module reports `channelsReady`.
 *
 * WHY A CONFIG PLUGIN AND NOT FILES IN android/
 * ---------------------------------------------
 * `apps/*​/android/` is gitignored and regenerated by `expo prebuild`, so
 * hand-written Kotlin in there is silently discarded — the exact failure mode
 * documented in `withAndroidNoSystemSplash.js` and `withAndroidReleaseSigning.js`.
 *
 * WHAT IS DELIBERATELY *NOT* DONE HERE
 * ------------------------------------
 * No custom `FirebaseMessagingService`. expo-notifications registers its own
 * and handles both notification- and data-messages natively; subclassing or
 * overriding it would mean re-implementing expo's dispatch, tap handling and
 * token plumbing, which is a large regression surface for no delivery gain.
 * The backend already ships a real `android.notification` block alongside the
 * data payload (see backend push.service.ts), so display is native and instant
 * without any JS involvement. The genuine gap was channel *existence*, and
 * that is what this plugin closes.
 */

/**
 * Channel definitions. MUST stay in sync with `src/lib/notifications.ts`.
 *
 * Importance is immutable after first creation, so the values below are also a
 * compatibility contract with devices that already created these channels from
 * the old JS path — changing an importance here has no effect on an existing
 * install and would only desync new ones.
 */
const CHANNELS = [
  // ─── Primary channels — what the backend targets via channelId ──────────
  {
    id: 'emergency_sos',
    name: 'Emergency Alerts',
    group: 'urgent',
    importance: 'IMPORTANCE_MAX',
    visibility: 'PUBLIC',
    vibration: [0, 500, 250, 500, 250, 500, 250, 500],
    lights: true,
    bypassDnd: true,
  },
  {
    id: 'approvals',
    name: 'Approvals',
    group: 'work',
    importance: 'IMPORTANCE_HIGH',
    visibility: 'PUBLIC',
    vibration: [0, 250, 250, 250],
  },
  {
    id: 'deliveries',
    name: 'Deliveries & Visitors',
    group: 'work',
    importance: 'IMPORTANCE_HIGH',
    visibility: 'PUBLIC',
    vibration: [0, 250, 250, 250],
  },
  {
    id: 'community',
    name: 'Community & Notices',
    group: 'general',
    importance: 'IMPORTANCE_DEFAULT',
    visibility: 'PRIVATE',
    vibration: [0, 200],
  },
  {
    id: 'payments',
    name: 'Payments & Salary',
    group: 'general',
    importance: 'IMPORTANCE_DEFAULT',
    visibility: 'PRIVATE',
    vibration: [0, 200],
  },
  {
    id: 'system',
    name: 'Account & System',
    group: 'general',
    importance: 'IMPORTANCE_DEFAULT',
    visibility: 'PRIVATE',
    vibration: [0, 200],
  },
  // ─── Legacy aliases — already exist on installed devices ────────────────
  // Kept at the SAME importance as the primary channel they map to so a
  // rolling backend deploy that still targets an old name behaves identically.
  {
    id: 'marketing',
    name: 'News & Updates',
    group: 'general',
    importance: 'IMPORTANCE_DEFAULT',
    visibility: 'PRIVATE',
    vibration: [0, 200],
  },
  {
    id: 'staff_tasks',
    name: 'Tasks',
    group: 'work',
    importance: 'IMPORTANCE_DEFAULT',
    visibility: 'PRIVATE',
    vibration: [0, 200],
  },
  {
    id: 'notices',
    name: 'Notices',
    group: 'general',
    importance: 'IMPORTANCE_DEFAULT',
    visibility: 'PRIVATE',
    vibration: [0, 200],
  },
  {
    id: 'approval_results',
    name: 'Approval Results',
    group: 'work',
    importance: 'IMPORTANCE_HIGH',
    visibility: 'PUBLIC',
    vibration: [0, 250, 250, 250],
  },
  {
    id: 'notices_urgent',
    name: 'Urgent Notices',
    group: 'urgent',
    importance: 'IMPORTANCE_HIGH',
    visibility: 'PUBLIC',
    vibration: [0, 250, 250, 250],
  },
  {
    id: 'default',
    name: 'General',
    group: 'general',
    importance: 'IMPORTANCE_HIGH',
    visibility: 'PRIVATE',
    vibration: [0, 250, 250, 250],
  },
  {
    id: 'sos',
    name: 'Emergency Alerts (legacy)',
    group: 'urgent',
    importance: 'IMPORTANCE_MAX',
    visibility: 'PUBLIC',
    vibration: [0, 500, 250, 500, 250, 500, 250, 500],
    lights: true,
    bypassDnd: true,
  },
];

const GROUPS = [
  { id: 'urgent', name: 'Urgent' },
  { id: 'work', name: 'Your work' },
  { id: 'general', name: 'General' },
];

/**
 * The channel FCM falls back to when a message names no/unknown channel.
 * MUST match `expo-notifications.defaultChannel` in app.json — that plugin owns
 * the manifest meta-data (see withManifestDefaults below).
 */
const DEFAULT_CHANNEL_ID = 'system';

const kotlinLongArray = (arr) => `longArrayOf(${arr.join(', ')})`;

function channelKotlin(c) {
  const lines = [
    `      NotificationChannel("${c.id}", "${c.name}", NotificationManager.${c.importance}).apply {`,
    `        lockscreenVisibility = Notification.VISIBILITY_${c.visibility}`,
    `        enableVibration(true)`,
    `        vibrationPattern = ${kotlinLongArray(c.vibration)}`,
    `        group = "${c.group}"`,
  ];
  if (c.lights) {
    lines.push(`        enableLights(true)`);
    lines.push(`        lightColor = BRAND_COLOR`);
  }
  if (c.bypassDnd) {
    // setBypassDnd() silently no-ops unless the user has granted the app
    // Do-Not-Disturb access. Requesting it is a separate user journey; setting
    // it here is still correct because it takes effect the moment access is
    // granted, without needing the channel to be recreated (which Android
    // would not allow anyway).
    lines.push(`        setBypassDnd(true)`);
  }
  lines.push(`      },`);
  return lines.join('\n');
}

const CHANNELS_KT = `package ${JAVA_PACKAGE}

import android.app.Application
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationChannelGroup
import android.app.NotificationManager
import android.content.Context
import android.os.Build
import android.util.Log

/**
 * Creates every notification channel this app uses, at process start.
 *
 * GENERATED by plugins/withNativeNotifications.js — do not edit in android/,
 * the folder is gitignored and rewritten by \`expo prebuild\`.
 *
 * Called from MainApplication.onCreate() BEFORE loadReactNative(), so the
 * channels exist even when the process was started by FCM to deliver a push to
 * a killed app — i.e. before any JavaScript has run. See the plugin header for
 * the full rationale.
 *
 * Channel creation is idempotent: re-creating an existing channel updates only
 * its name/description. Importance, vibration and DND policy are locked to
 * whatever the channel had when it was FIRST created, which is precisely why
 * getting them right on the very first run matters.
 */
object MarziNotificationChannels {
  private const val TAG = "MarziChannels"
  private const val BRAND_COLOR = 0xFF821A52.toInt()

  /** Channel FCM falls back to; mirrored in the manifest meta-data. */
  const val DEFAULT_CHANNEL_ID = "${DEFAULT_CHANNEL_ID}"

  @Volatile
  private var created = false

  @JvmStatic
  fun ensure(context: Context) {
    if (created) return
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
      created = true
      return
    }
    val nm = context.getSystemService(Context.NOTIFICATION_SERVICE) as? NotificationManager
    if (nm == null) {
      Log.w(TAG, "NotificationManager unavailable; channels not created")
      return
    }
    try {
      nm.createNotificationChannelGroups(
        listOf(
${GROUPS.map((g) => `          NotificationChannelGroup("${g.id}", "${g.name}"),`).join('\n')}
        )
      )
      nm.createNotificationChannels(
        listOf(
${CHANNELS.map(channelKotlin).join('\n')}
        )
      )
      created = true
    } catch (t: Throwable) {
      // Never let channel setup take down app start. A failure here degrades
      // to Android's default channel behaviour, which is survivable; a crash
      // in Application.onCreate is not.
      Log.e(TAG, "Failed to create notification channels", t)
    }
  }

  @JvmStatic
  fun isReady(): Boolean = created
}
`;

const MODULE_KT = `package ${JAVA_PACKAGE}

import android.app.NotificationManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.provider.Settings
import androidx.core.app.NotificationManagerCompat
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.WritableArray

/**
 * Diagnostics + deep-link bridge for Android notification settings.
 *
 * GENERATED by plugins/withNativeNotifications.js.
 *
 * Classic (non-Turbo) ReactContextBaseJavaModule because this app runs on the
 * OLD architecture (\`newArchEnabled: false\` — required by the splash-hang fix).
 *
 * WHY THESE METHODS
 * -----------------
 * The single most common "notifications don't work" report is not a missing
 * app-level permission — it is ONE channel silently switched off, or the whole
 * app blocked at the OS level, both of which the JS-side
 * \`Notifications.getPermissionsAsync()\` reports as \`granted\`. \`getChannelStatus\`
 * exposes the real per-channel importance so the app can tell the user exactly
 * which alert type is muted and deep-link them straight to that channel's
 * system screen instead of dumping them in app settings to hunt for it.
 */
class MarziNotificationsModule(private val reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = "MarziNotifications"

  override fun getConstants(): MutableMap<String, Any> = hashMapOf(
    // Lets JS skip its own ~14 async channel-creation round-trips on login.
    "channelsReady" to MarziNotificationChannels.isReady(),
    "defaultChannelId" to MarziNotificationChannels.DEFAULT_CHANNEL_ID,
  )

  /** True when the user has not blocked notifications for the whole app. */
  @ReactMethod
  fun areNotificationsEnabled(promise: Promise) {
    try {
      promise.resolve(NotificationManagerCompat.from(reactContext).areNotificationsEnabled())
    } catch (t: Throwable) {
      promise.reject("E_NOTIF_STATE", t)
    }
  }

  /**
   * Per-channel state: importance plus whether the channel's GROUP is blocked
   * (a blocked group mutes every channel in it while each channel still
   * reports its own importance, which is a genuinely confusing Android
   * behaviour worth surfacing explicitly).
   *
   * importance: -1000 = channel missing, 0 = user turned this channel OFF.
   */
  @ReactMethod
  fun getChannelStatus(promise: Promise) {
    try {
      val out: WritableArray = Arguments.createArray()
      if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
        promise.resolve(out)
        return
      }
      val nm = reactContext.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
      for (channel in nm.notificationChannels) {
        val map = Arguments.createMap()
        map.putString("id", channel.id)
        map.putString("name", channel.name?.toString() ?: channel.id)
        map.putInt("importance", channel.importance)
        map.putBoolean("blocked", channel.importance == NotificationManager.IMPORTANCE_NONE)
        val groupId = channel.group
        map.putString("groupId", groupId)
        var groupBlocked = false
        if (groupId != null && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
          groupBlocked = nm.getNotificationChannelGroup(groupId)?.isBlocked ?: false
        }
        map.putBoolean("groupBlocked", groupBlocked)
        out.pushMap(map)
      }
      promise.resolve(out)
    } catch (t: Throwable) {
      promise.reject("E_CHANNEL_STATUS", t)
    }
  }

  /** Open the OS settings page for ONE channel (Android O+), else app settings. */
  @ReactMethod
  fun openChannelSettings(channelId: String, promise: Promise) {
    try {
      val intent = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        Intent(Settings.ACTION_CHANNEL_NOTIFICATION_SETTINGS)
          .putExtra(Settings.EXTRA_APP_PACKAGE, reactContext.packageName)
          .putExtra(Settings.EXTRA_CHANNEL_ID, channelId)
      } else {
        appSettingsIntent()
      }
      launch(intent)
      promise.resolve(true)
    } catch (t: Throwable) {
      // Some OEM ROMs ship without the per-channel screen. Fall back rather
      // than leaving the user on a dead button.
      try {
        launch(appSettingsIntent())
        promise.resolve(true)
      } catch (t2: Throwable) {
        promise.reject("E_OPEN_CHANNEL", t2)
      }
    }
  }

  /** Open this app's notification settings screen. */
  @ReactMethod
  fun openNotificationSettings(promise: Promise) {
    try {
      launch(appSettingsIntent())
      promise.resolve(true)
    } catch (t: Throwable) {
      promise.reject("E_OPEN_SETTINGS", t)
    }
  }

  private fun appSettingsIntent(): Intent =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS)
        .putExtra(Settings.EXTRA_APP_PACKAGE, reactContext.packageName)
    } else {
      Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS)
        .setData(Uri.fromParts("package", reactContext.packageName, null))
    }

  /**
   * Prefer the foreground activity so the settings screen lands on top of the
   * app's own task; only fall back to NEW_TASK from the application context,
   * which on some OEMs otherwise opens settings in a separate recents entry.
   */
  private fun launch(intent: Intent) {
    val activity = reactContext.currentActivity
    if (activity != null) {
      activity.startActivity(intent)
    } else {
      intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
      reactContext.startActivity(intent)
    }
  }
}
`;

const PACKAGE_KT = `package ${JAVA_PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * GENERATED by plugins/withNativeNotifications.js.
 *
 * Registered manually in MainApplication.getPackages() — autolinking only
 * covers node_modules, not app-local native code.
 */
class MarziNativePackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(MarziNotificationsModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;

const FILES = {
  'MarziNotificationChannels.kt': CHANNELS_KT,
  'MarziNotificationsModule.kt': MODULE_KT,
  'MarziNativePackage.kt': PACKAGE_KT,
};

/** Drop the Kotlin sources into the (regenerated) android project. */
const withKotlinSources = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'java',
        ...JAVA_PACKAGE.split('.'),
      );
      fs.mkdirSync(dir, { recursive: true });
      for (const [name, contents] of Object.entries(FILES)) {
        fs.writeFileSync(path.join(dir, name), contents, 'utf8');
      }
      return cfg;
    },
  ]);

/**
 * Register the package and create channels before React Native loads.
 *
 * Order matters: `ensure()` runs BEFORE `loadReactNative(this)` so a
 * push-triggered process start has its channels in place even if the JS bundle
 * never finishes loading.
 */
const withMainApplicationHooks = (config) =>
  withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;

    if (!src.includes('MarziNativePackage()')) {
      const anchor = 'PackageList(this).packages.apply {';
      if (!src.includes(anchor)) {
        throw new Error(
          '[with-native-notifications] Could not find PackageList anchor in MainApplication',
        );
      }
      src = src.replace(anchor, `${anchor}\n              add(MarziNativePackage())`);
    }

    if (!src.includes('MarziNotificationChannels.ensure')) {
      const anchor = 'loadReactNative(this)';
      if (!src.includes(anchor)) {
        throw new Error(
          '[with-native-notifications] Could not find loadReactNative anchor in MainApplication',
        );
      }
      src = src.replace(
        anchor,
        `// Channels must exist before ANY notification can be delivered —\n` +
          `    // including on a process that FCM started to deliver a push to a\n` +
          `    // killed app, where JS may never run. See\n` +
          `    // plugins/withNativeNotifications.js.\n` +
          `    MarziNotificationChannels.ensure(this)\n` +
          `    ${anchor}`,
      );
    }

    cfg.modResults.contents = src;
    return cfg;
  });

/**
 * Declares ACCESS_NOTIFICATION_POLICY so `setBypassDnd(true)` on the emergency
 * channel can take effect once the user grants Do-Not-Disturb access.
 *
 * NOTE — the FCM `default_notification_channel_id` meta-data is deliberately
 * NOT set here. expo-notifications' own manifest mod actively REMOVES that key
 * whenever its `defaultChannel` prop is unset, and it runs after this plugin,
 * so anything written here is silently deleted. It is configured instead via
 * the `expo-notifications` plugin props in app.json (`"defaultChannel":
 * "system"`), which is the supported path and survives plugin reordering.
 */
const withManifestDefaults = (config) =>
  withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    manifest['uses-permission'] = manifest['uses-permission'] ?? [];
    const has = (n) => manifest['uses-permission'].some((p) => p.$?.['android:name'] === n);
    if (!has('android.permission.ACCESS_NOTIFICATION_POLICY')) {
      manifest['uses-permission'].push({
        $: { 'android:name': 'android.permission.ACCESS_NOTIFICATION_POLICY' },
      });
    }
    return cfg;
  });

const withNativeNotifications = (config) =>
  withManifestDefaults(withMainApplicationHooks(withKotlinSources(config)));

module.exports = createRunOncePlugin(withNativeNotifications, pkg.name, pkg.version);
