export { ApiClient } from './client';
export type { ApiClientConfig, TokenPair } from './client';
export { unwrapApiEnvelope } from './envelope';
export type { ApiSuccessEnvelope } from './envelope';
export type {
  ApiError,
  PaginatedResponse,
  AuthUser,
  AuthResponse,
  VerifyOtpUserPayload,
  VerifyOtpTotpChallenge,
  VerifyOtpSuccessPayload,
  VerifyOtpPayload,
  AdminVerifyOtpUser,
  AdminVerifyOtpSuccessPayload,
  AdminVerifyOtpPayload,
  Society,
  Unit,
  Resident,
  Visitor,
  VisitorStatus,
  ServiceRequest,
  ServiceRequestStatus,
  Complaint,
  ComplaintStatus,
  Notice,
  NoticeCategory,
  Society_Event,
  EventCategory,
  MaintenanceBill,
  BillBreakdown,
  SosAlert,
  SosStatus,
  StaffUser,
  AttendanceRecord,
  AttendanceStatus,
  LeaveRequest,
  LeaveStatus,
  LeaveType,
  Doctor,
  Appointment,
  DashboardStats,
} from './types';
export { isVerifyOtpTotpChallenge } from './types';
